import  math

print(math.pi)
print(math.inf)
print("*************************")
print(math.ceil(1.4))
print(math.floor(1.4))
print(math.ceil(5.3))
print(math.floor(5.3))
print(math.ceil(-5.3))
print(math.floor(-5.3))
print(math.ceil(22.6))
print(math.floor(22.0))
print(math.ceil(10.0))
print(math.floor(10.0))
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print(math.cos(0.00))
print(math.cos(10))
print(math.cos(3.1415926))
print(math.sin(1.00))
print(math.sin(0))

print("_______________________________")
print(math.degrees(8.90))
print(math.degrees(-20))
print(math.degrees(1))
print(math.degrees(90))

print("###########################")
print(math.fabs(-25.45))
print(math.fabs(-8))
print("%%%%%%%%%%%%%%%%%%%")
print(math.factorial(5))
print("******************************")
print(math.fmod(20,4))
print(math.fmod(45,2))
print(math.fmod(12,7))
print("----------------------")
print(math.fsum([10,20,30,40,50,60]))
print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
print(math.prod([1,2,3,4,5]))
print("*******************************")
print(math.gcd(2,4,6,8,10))
print("--------------------------")
print(math.isfinite(5))
print("-----------------------")
print(math.isinf(10))
print("**************************************")
print(math.isnan(math.nan))
print("---------------------------")
print(math.pow(2,3))
print("-------------------------")
print(math.sqrt(25))




